name: Build and/or Publish

on:
  push: 
  workflow_dispatch: 

env:
  POWEREDBY: ossmht

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: poetry install
      shell: bash
      run: |
        pip install poetry
        poetry install --with dev
        poetry self add "poetry-dynamic-versioning[plugin]"
    - name: build_wheel
      shell: bash
      id: build_whl
      run: |
        poetry build
    - name: upload built artifacts
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/*.whl

  create_release:
    runs-on: ubuntu-latest
    name: creates release and uploads whl to release
    needs: [build]
    permissions:
      contents: write
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        # pattern: python-package-distributions-*
        # merge-multiple: true
        path: dist   
    - name: list dist dir
      run: |
        pwd
        ls -lrt dist/
    - name: Upload wheel to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/*.whl
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true

  publish_test_PyPi:
    name: Publish to test.pypi.org/
    runs-on: ubuntu-latest
    needs: [create_release]
    permissions:
      id-token: write
      contents: write
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        # pattern: python-package-distributions-*
        # merge-multiple: true
        path: dist   
    - name: Publish
      uses: pypa/gh-action-pypi-publish@release/v1
      with: # added
        repository-url: https://test.pypi.org/legacy/
        verbose: true
        attestations: false

  publish_PyPi:
    name: Publish to pypi.org/
    runs-on: ubuntu-latest
    needs: [publish_test_PyPi]
    permissions:
      id-token: write
      contents: write
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        # pattern: python-package-distributions-*
        # merge-multiple: true
        path: dist
    - name: Publish
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        verbose: true
        attestations: false
